version: '3.8'


services:
  # Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: medical-appointments-app
    restart: always
    ports:
      - "9091:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/medical_appointments
      - JDBC_DATABASE_USERNAME=${DB_USER:-postgres}
      - JDBC_DATABASE_PASSWORD=${DB_PASSWORD:-changeMe123!}
      - PROD_ADMIN_USERNAME=${ADMIN_USER:-admin}
      - PROD_ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeMe456!}
    volumes:
      - app-logs:/var/log/medical-appointments
    networks:
      - app-network

  # Database
  db:
    image: postgres:16-alpine
    container_name: medical-appointments-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=medical_appointments
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeMe123!}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # pgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4
    container_name: medical-appointments-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-changeMe789!}
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

volumes:
  db-data:
  app-logs:
  pgadmin-data:

networks:
  app-network:
    driver: bridge 
