version: '3.8'

services:
  # Application with hot reloading
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: medical-appointments-app-dev
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/medical_appointments
      - JDBC_DATABASE_USERNAME=${DB_USER:-postgres}
      - JDBC_DATABASE_PASSWORD=${DB_PASSWORD:-changeMe123!}
    volumes:
      - ./src:/app/src  # Mount source code for hot reloading
      - app-logs:/var/log/medical-appointments
    networks:
      - app-network

  # Database
  db:
    image: postgres:13-alpine
    container_name: medical-appointments-db-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=medical_appointments
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeMe123!}
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # pgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4
    container_name: medical-appointments-pgadmin-dev
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-changeMe789!}
    volumes:
      - pgadmin-data-dev:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data-dev:
  app-logs:
  pgadmin-data-dev:
